

[[project]]
title = "Plus"
category = "Product Management"
image = "./config/assets/projects/Plus.jpg"
url = "https://github.com/Umesh1610/plus"

[[project]]
title = "Customer Parkway Preschool"
category = "Project Management"
image = "./config/assets/projects/cpp.png"
url = "https://github.com/Umesh1610/Custer-Parkway-Preschool"

[[project]]
title = "Cred"
category = "Product Strategy"
image = "./config/assets/projects/Cred.png"
url = "https://github.com/Umesh1610/Cred-Case-Study"

[[project]]
title = "Linkedin"
category = "Product Ideation"
image = "./config/assets/projects/Linkedin.png"
url = "https://github.com/Umesh1610/Linkedin"

[[project]]
title = "Retail Customer Analysis"
category = "Data Analysis"
image = "./config/assets/projects/rca.png"
url = "https://github.com/Umesh1610/Retail-Customer-Analysis"

[[project]]
title = "Restaurant Booking"
category = "Product Management"
image = "./config/assets/projects/Restaurant booking.png"
url = "https://github.com/Umesh1610/Restaurant-Booking"

[[project]]
title = "Phonepe"
category = "Product Management"
image = "./config/assets/projects/phonepe.png"
url = "https://github.com/Umesh1610/Phonepe-Strategy"

