############## Education config #################
#################################################
[[education]]
title = "Dhirubhai Ambani Institue of Information and Communication Technology"
timeline = "2015 — 2019"
description = "Bachelor of Technology in Computer Science"

[[education]]
title = "University of Texas at Dallas"
timeline = "2022 — 2024"
description = "Master of Science in Information Technology Management. Dean's excellence Scholar and Teaching Assitant for Digital Product Management"



############## Experience config ################
#################################################
[[experience]]
title = "Data Analyst Intern, Capillary Technologies"
timeline = "2019 — 2019"
description = "Developed dynamic dashboards and automated models to support and enhance strategic decision making"

[[experience]]
title = "Associate, Analytics, Capillary Technologies "
timeline = "2019 — 2021"
description = "Drove customer reactivation and reduced churn by optimizing analytical processes and implementing strategic campaigns."

[[experience]]
title = "Senior Associate, Analytics, Capillary Technologies "
timeline = "2021 — 2022"
description = "Led analytics for major accounts, streamlining processes and improving client outcomes through data-informed strategies."

[[experience]]
title = "Product Manager, Honeywell "
timeline = "2023 — 2023"
description = "Improved product adoption, leading to significant lift in efficiency and user satisfaction."


############## Skills config ####################
#################################################
[skills] 
title = "My Skills"
enabled = true
show_bar = true
show_value = true

[[skill]]
title = "Data Analysis"
value = "80%"

[[skill]]
title = "SQL"
value = "90%"

[[skill]]
title = "Excel"
value = "90%"

[[skill]]
title = "Presentation"
value = "70%"

############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = true
show_value = true

[[language]]
title = "SQL"
value = "90%"

[[language]]
title = "Python"
value = "60%"
