############### Section config ##################
#################################################
title = "Tech Experience"
enabled = true # false

############### Technologies ####################
#################################################
# Technology I have worked with
# name = "./.../../icon_path"
[technologies]
figma = "./config/assets/icons/figma.svg"
jira = "./config/assets/icons/jira.svg"
mysql = "./config/assets/icons/mysql.svg"
tableau = "./config/assets/icons/tableau.svg"
powerbi = "./config/assets/icons/powerbi.svg"
pandas = "./config/assets/icons/pandas.svg"
mongodb = "./config/assets/icons/mongodb.svg"
databricks = "./config/assets/icons/databricks.svg"
html = "./config/assets/icons/html.svg"
balsmiq = "./config/assets/icons/balsmiq.svg"
jupyter = "./config/assets/icons/jupyter.svg"
